name = "TWCraft"
author = "hekatonk"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fb9e817f6bd700d8988419ee8d1fc31bdf68ef718cccd74241806e297a5fd05"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
