name = "TWCraft"
author = "hekatonk"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63aa9366249b9a63a5553b92e40bc14171751e091bf4a62f49b921b102543d71"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
