name = "TWCraft"
author = "hekatonk"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23ff64a9f3e01fae35d8aad82f40a5f498679a2fcd9ef6b72a65cc007473086c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
